// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IVault } from "@balancer-labs/v2-interfaces/contracts/vault/IVault.sol";

interface IRelayerLibrarySystem {
  function getVault() external view returns (IVault);

  function swap(
    IVault.SingleSwap memory singleSwap,
    IVault.FundManagement calldata funds,
    uint256 limit,
    uint256 deadline,
    uint256 value
  ) external payable returns (uint256);

  function updateEntryPoint() external returns (address);

  function increment() external returns (uint32);
}
